version: '3'

services:
  visualsync-pro:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./assets:/app/assets
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
